//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 05:43:30 AM IST 
//


package com.example.xml.newuser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.xml.newuser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.xml.newuser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewUserProfileResponse }
     * 
     */
    public NewUserProfileResponse createNewUserProfileResponse() {
        return new NewUserProfileResponse();
    }

    /**
     * Create an instance of {@link NewUserProfileRequest }
     * 
     */
    public NewUserProfileRequest createNewUserProfileRequest() {
        return new NewUserProfileRequest();
    }

    /**
     * Create an instance of {@link UserProfile }
     * 
     */
    public UserProfile createUserProfile() {
        return new UserProfile();
    }

}
